
spring:
  rabbitmq:
    host: 43.133.192.187  # mq?????
    port: 5672
    virtual-host: /hmall  # ??????
    username: hmall # ???
    password: 123456
    connection-timeout: 1s
    template:
      retry:
        enabled: true # ????????
        initial-interval: 1000ms # ??????????
        multiplier: 1 # ??????????????????? = initial-interval * multiplier
        max-attempts: 3 # ??????
    publisher-confirm-type: none # ??publisher confirm??????confirm??
    publisher-returns: false # ??publisher return??
logging:
  level:
    com.my: debug
