spring:
  rabbitmq:
    host: 43.133.192.187  # mq?????
    port: 5672
    virtual-host: /hmall  # ??????
    username: hmall # ???
    password: 123456
    listener:
      simple:
        # 预取机制是指在消费者端的缓冲区中提前获取一定数量的消息，这样可以提高消费者的效率，减少了网络交互的次数。
        # 每次只能获取一条消息，处理完成才能获取下一个消息
        prefetch: 1
        acknowledge-mode: auto #消费者消息确认模式
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
logging:
  level:
    com.my: debug
